#!/bin/sh

### BEGIN INIT INFO
# Provides:Provides  tris3d
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tris3d multiplayer server
# Description:       starts tris3d multiplayer server and play tic tac toe in 3d
### END INIT INFO

start() {
  su -c 'cd /opt/tris3d-server; npm start' -s /bin/bash USER 1> /dev/null
}

stop() {
  su -c 'cd /opt/tris3d-server; npm start' -s /bin/bash USER 1> /dev/null
}

case "$1" in
  start)
    start
    exit 0
  ;;
  stop)
    stop
    exit 0
  ;;
  restart)
    stop
    start
    exit 0
  ;;
  **)
    echo "Usage: $0 {start|stop|restart}" 1>&2
    exit 1
  ;;
esac
